---
- name: Ensure App is Running
  hosts: localhost
  gather_facts: false
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  tasks:
    - name: Get AKS credentials
      shell: "az login --service-principal --username {{ lookup('env','AZURE_CLIENT_ID') }} --password {{ lookup('env','AZURE_SECRET') }} --tenant {{ lookup('env','AZURE_TENANT') }} && rm -f /var/jenkins_home/.kube/config && az aks get-credentials --resource-group {{ lookup('env','RESOURCE_GROUP') }} --name {{ lookup('env','AKS_NAME') }}"
    - name: Get IP
      shell: "kubectl get services {{ lookup('env','IMAGE_NAME') }}service | awk '{if(NR>1)print $4}'"
      register: ip
      until: ip.stdout != "<pending>"
      retries: 20
      delay: 3
    - name: Ensure pod deployed
      shell: "kubectl get pods | grep demoapp | awk '{print $3}'"
      register: running
      until: running.stdout == "Running"
      retries: 10
      delay: 3
    - name: Testing app access / running
      uri:
        url: "http://{{ ip.stdout }}:8080/PolishedDemo/"
      register: result
      until: result.status == 200
      retries: 10
      delay: 3
    - name: Testing RestWebServices atickets
      uri:
        url: "http://{{ ip.stdout }}:8080/RestWebServices/atickets"
      register: result
      until: result.status == 200
      retries: 10
      delay: 3
    - name: Testing RestWebServices btickets
      uri:
        url: "http://{{ ip.stdout }}:8080/RestWebServices/btickets"
      register: result
      until: result.status == 200
      retries: 10
      delay: 3
    - name: Testing RestWebServices ctickets
      uri:
        url: "http://{{ ip.stdout }}:8080/RestWebServices/ctickets"
      register: result
      until: result.status == 200
      retries: 10
      delay: 3
    - name: Testing SOAPWebServices
      uri:
        url: "http://{{ ip.stdout }}:8080/SoapWebServices/ShiftWs?wsdl"
      register: result
      until: result.status == 200
      retries: 10
      delay: 3
